version: '3.7'

services:
  apps:
    build: 
      context: .
      dockerfile: ./docker/apps/Dockerfile
    ports:
      - "3000:3000"
      - "8000:8000"
    networks:
      - common_link
    command: "pnpm start:dev"
    volumes:
      - "./apps:/apps"
    depends_on:
      - db
      - redis
      - minio
  redis:
    image: "redis:latest"
    build: 
      context: .
      dockerfile: ./docker/redis/Dockerfile
    networks:
      - common_link
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  db:
    image: "mysql:latest"
    build: 
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - common_link
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
  minio:
    image: minio/minio:latest@sha256:ea15e53e66f96f63e12f45509d2d2d8fad774808debb490f48508b3130bd22d3
    volumes:
      - ./data/minio:/xxx/minio/data
    ports:
        - 9000:9000
        - 9001:9001
    environment:
        MINIO_ROOT_USER: "minio_root"
        MINIO_ROOT_PASSWORD: "minio_password"
    networks:
      - common_link
    command: server --console-address ":9001" /xxx/minio/data

networks:
  common_link:
    external: true
