name: build-test

on:
  push:

jobs:
  build-test:
    name: Build test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: ESlint Format Test
        run: pnpm run lint
